language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

sudo: false
cache:
  - cargo
  - pip
before_script:
  - pip install --user nose PySocks shadowsocks
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin/:$PATH
script:
  - cargo test
  - bash tests/test.sh
after_failure:
  - cat /tmp/ssc.log
  - cat /tmp/sss.log

notifications:
  email:
    on_failure: change
    on_success: change
