build: false

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.12"
  PYTHON_ARCH: "32"

  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;%PYTHON%/Scripts/
  - rustc -V
  - cargo -V
  - pip install nose PySocks

test_script:
  - cargo test
  - cargo run --bin ssserver -- -h
  # - ps: mv target\debug\shadowsocks.exe ssserver.exe
  - cargo run --bin sslocal --features="sslocal" -- -h
  # - ps: mv target\debug\shadowsocks.exe sslocal.exe
  # - ssserver.exe -h
  # - sslocal.exe -h
  # - ps: Start-Process ssserver.exe -ArgumentList '-c tests\config\server_conf.toml --log-file ssserver.log'
  # - ps: Start-Process sslocal.exe -ArgumentList '-c tests\config\local_conf.toml --log-file sslocal.log'
  # - ps: Start-Process python -ArgumentList 'tests\echo_server.py'
  # - nosetests tests\test_tcp.py
  # - nosetests tests\test_udp.py
